Document all NumPy and pandas concepts covered this week in a clean notebook.

In [1]:
import numpy as np
import pandas as pd

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

[10 20 30 40 50]
Shape: (5,)
Size: 5
Dimensions: 1


In [3]:
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[::-1])

10
50
[20 30 40]
[50 40 30 20 10]


In [4]:
print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 2)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [ 5. 10. 15. 20. 25.]


In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])

reshaped = arr.reshape(2, 3)

print("Reshaped:")
print(reshaped)

print("Flattened:")
print(reshaped.flatten())

Reshaped:
[[10 20 30]
 [40 50 60]]
Flattened:
[10 20 30 40 50 60]


In [6]:
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 35.0
Median: 35.0
Standard Deviation: 17.07825127659933


In [7]:
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

matrix2 = np.array([
    [5, 6],
    [7, 8]
])

print("Addition:")
print(matrix1 + matrix2)

print("Multiplication:")
print(matrix1 * matrix2)

print("Matrix Multiplication:")
print(matrix1 @ matrix2)

Addition:
[[ 6  8]
 [10 12]]
Multiplication:
[[ 5 12]
 [21 32]]
Matrix Multiplication:
[[19 22]
 [43 50]]


In [8]:
marks = pd.Series(
    [85, 72, 90, 65, 78],
    index=["Math", "Science", "English", "History", "Computer"]
)

print(marks)
print(marks["Math"])
print(marks[marks > 75])

Math        85
Science     72
English     90
History     65
Computer    78
dtype: int64
85
Math        85
English     90
Computer    78
dtype: int64


In [9]:
data = {
    "Name": ["Vijay", "Rahul", "John", "David"],
    "Age": [24, 25, 23, 26],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0  Vijay   24     85
1  Rahul   25     90
2   John   23     78
3  David   26     92


In [10]:
print(df.head())
print(df.tail())

df.info()

print(df.describe())

    Name  Age  Marks
0  Vijay   24     85
1  Rahul   25     90
2   John   23     78
3  David   26     92
    Name  Age  Marks
0  Vijay   24     85
1  Rahul   25     90
2   John   23     78
3  David   26     92
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   Marks   4 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes
             Age      Marks
count   4.000000   4.000000
mean   24.500000  86.250000
std     1.290994   6.238322
min    23.000000  78.000000
25%    23.750000  83.250000
50%    24.500000  87.500000
75%    25.250000  90.500000
max    26.000000  92.000000


In [11]:
print(df["Name"])

print(df[["Name", "Marks"]])

print(df[df["Marks"] > 80])

0    Vijay
1    Rahul
2     John
3    David
Name: Name, dtype: object
    Name  Marks
0  Vijay     85
1  Rahul     90
2   John     78
3  David     92
    Name  Age  Marks
0  Vijay   24     85
1  Rahul   25     90
3  David   26     92


In [12]:
df.loc[1, "Marks"] = np.nan

print(df.isnull().sum())

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

print(df)

Name     0
Age      0
Marks    1
dtype: int64
    Name  Age  Marks
0  Vijay   24   85.0
1  Rahul   25   85.0
2   John   23   78.0
3  David   26   92.0


In [13]:
df["Bonus"] = df["Marks"] + 5

print(df)

    Name  Age  Marks  Bonus
0  Vijay   24   85.0   90.0
1  Rahul   25   85.0   90.0
2   John   23   78.0   83.0
3  David   26   92.0   97.0


In [14]:
data = {
    "Name": ["Vijay", "Rahul", "John", "David"],
    "Department": ["IT", "HR", "IT", "HR"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print(df.groupby("Department")["Marks"].mean())

print(df.groupby("Department")["Name"].count())

Department
HR    91.0
IT    81.5
Name: Marks, dtype: float64
Department
HR    2
IT    2
Name: Name, dtype: int64


In [15]:
data = {
    "Name": ["Vijay", "Rahul", "John", "David", "Mike"],
    "Math": [85, 90, np.nan, 92, 78],
    "Science": [80, 85, 75, np.nan, 82],
    "English": [90, 88, 82, 95, np.nan]
}

df = pd.DataFrame(data)

df["Math"] = df["Math"].fillna(df["Math"].mean())
df["Science"] = df["Science"].fillna(df["Science"].mean())
df["English"] = df["English"].fillna(df["English"].mean())

df["Total"] = df["Math"] + df["Science"] + df["English"]
df["Percentage"] = df["Total"] / 3

print(df)

print("\nAverage Percentage:", df["Percentage"].mean())
print("Highest Percentage:", df["Percentage"].max())
print("Lowest Percentage:", df["Percentage"].min())

    Name   Math  Science  English   Total  Percentage
0  Vijay  85.00     80.0    90.00  255.00   85.000000
1  Rahul  90.00     85.0    88.00  263.00   87.666667
2   John  86.25     75.0    82.00  243.25   81.083333
3  David  92.00     80.5    95.00  267.50   89.166667
4   Mike  78.00     82.0    88.75  248.75   82.916667

Average Percentage: 85.16666666666667
Highest Percentage: 89.16666666666667
Lowest Percentage: 81.08333333333333
